services:
  app:
    build: .
    ports:
      - "9000:9000"
    environment:
      MONGO_URL: mongodb://mongo:27017/made-in-cameroon
      NODE_ENV: development
    env_file:
      - .env
    depends_on:
      - mongo

  redis: 
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      
  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  redis_data:
  mongo-data: